@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


    title Целевая архитектура данных компании "Будущее 2.0" (через год)

    Person(operator, "Бизнес-пользователь", "Сотрудник головного офиса, клиники, финтеха")

    System_Ext(ext_sys, "Внешние партнеры", "Фармкомпании, производители электроники")

    Boundary(portal, "Портал самообслуживания (Data Mesh)") {
        Container(web_app, "Веб-приложение", "React", "Единая точка доступа к витринам данных. Конструктор отчетов, дашборды. Аутентификация и авторизация через корпоративный SSO.")
        Container(api_gateway, "API Gateway", "Kong / APIM", "Управляет доступом к данным. Маршрутизирует запросы к продуктам данных разных доменов на основе прав доступа пользователя.")
    }

    Boundary(cloud, "Облачная инфраструктура", "Геораспределенное развертывание для отказоустойчивости") {



        Boundary(domain_fintech, "Домен: Финтех") {
            ContainerDb(fintech_dwh, "Хранилище данных финтеха", "Greenplum / ClickHouse", "Содержит агрегированные финансовые данные, данные о кредитах, счетах. Медицинские данные исключены.")
            Container(fintech_etl, "Сервисы поставки данных", "Apache Airflow / Spark", "Извлекает финансовые данные из операционных систем Финтеха, преобразует и загружает в DWH домена.")
            Container(fintech_product, "Продукты данных Финтеха", "REST API на Go / gRPC", "Предоставляет  датасеты Финтеха. Публикует API в каталог.")
        }

        Boundary(domain_ai, "Домен: ИИ-сервисы") {
            ContainerDb(ai_dwh, "Аналитическая БД ИИ", "PostgreSQL / S3 Data Lake", "Хранит обезличенные результаты анализов ИИ, логи работы моделей, метрики точности. Никаких исходных медицинских карт.")
            Container(ai_etl, "Сервисы сбора данных", "Python / MLflow", "Поставляет данные из контура работы моделей в аналитическую БД домена.")
            Container(ai_product, "Продукты данных ИИ", "REST API на Python", "Предоставляет датасеты ИИ. Публикует API в каталог.")
        }

        Boundary(domain_clinic, "Домен: Клиники", "Ключевое ядро, обеспечивающее целостность мед. данных") {
            ContainerDb(ops_db, "Операционная БД клиник", "Aurora PostgreSQL", "Новая система-преемник легаси DWH для операционных процессов. Хранит мед. карты, истории, снимки (через ссылки на S3). Строгий контроль доступа.")
            Container(esb, "Брокер сообщений", "Apache Kafka")
            Container(esb_service, "Интеграционный сервис", "Spring/Java", "Обеспечивает событийную интеграцию между ИИ-модулями, рабочим местом врача и аналитикой в режиме real-time.")
            Container(clinical_product, "Продукты данных клиник", "REST API на Java", "Предоставляет обезличенные и агрегированные датасеты: «Загрузка клиник», «Эффективность лечения», «Отчеты для Минздрава». Публикует API в каталоге.")
        }
    }

    Boundary(catalog, "Глобальный каталог данных") {
        Container(data_catalog, "Data Catalog", "Apache Atlas / Collibra", "Централизованный реестр всех продуктов данных. Пользователь портала ищет нужный датасет здесь и получает ссылку на API конкретного домена.")
        Container(governance, "Data Governance", "Сервис правил", "Хранит и применяет глобальные политики качества данных, управления мастер-данными (MDM) и прав доступа.")
    }

    Rel(operator, web_app, "Создает отчет, строит дашборд", "HTTPS")
    Rel(web_app, api_gateway, "Запрос данных от имени пользователя", "REST")
    Rel(api_gateway, data_catalog, "Поиск нужного продукта данных", "REST")
    Rel(api_gateway, fintech_product, "Запрос финансовых данных", "REST/HTTP")
    Rel(api_gateway, ai_product, "Запрос данных об ИИ-моделях", "REST/HTTP")
    Rel(api_gateway, clinical_product, "Запрос операционных и агрегированных данных по клиникам", "REST/HTTP")

    Rel(fintech_etl, fintech_dwh, "Загрузка агрегированных данных", "JDBC/ETL")
    Rel(fintech_product, fintech_dwh, "Чтение подготовленных витрин", "JDBC")
    Rel(ai_etl, ai_dwh, "Загрузка данных моделей", "JDBC/API")
    Rel(ai_product, ai_dwh, "Чтение витрин", "JDBC")

    Rel(clinical_product,ops_db, "Чтение подготовленных витрин", "JDBC")
    Rel(esb, esb_service, "Передача данных в реальном времени", "Kafka Streams")
    Rel(esb_service, ops_db, "Передача данных в реальном времени", "JDBC")
    Rel(ext_sys, api_gateway, "Безопасный обмен данными", "HTTPS/REST")
@enduml